version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean install -P dev
artifacts: 
  files:
    - 'target/HelloWorld.war'
  name: HelloWorld
  discard-paths: yes