version: 0.2
env:
  variables:
    SONAR_TOKEN: "8c9234de918067841f3d5f033a4e31252bf656ec"
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      # mvn ${groupId}:${artifactId}:${goal}
      - mvn org.apache.maven.plugins:maven-war-plugin:3.3.2:validate
      - mvn clean verify sonar:sonar \
        -Dsonar.login=8c9234de918067841f3d5f033a4e31252bf656ec \
        -Dsonar.projectKey=codecommit_sonar
      # - mvn clean install
artifacts: 
  files:
    - 'target/HelloWorld.war'
  name: HelloWorld
  discard-paths: yes